// @vitest-environment node

import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import request from 'supertest';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { createAgentBridgeHttpServer } from '../../../bridge/http/server';
import { readVaultManifest } from '../../../bridge/vault/intake';

let app: Awaited<ReturnType<typeof createAgentBridgeHttpServer>>;
let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(tmpdir(), 'html-native-http-bridge-'));
  app = await createAgentBridgeHttpServer();
  await app.ready();
});

afterEach(async () => {
  await app.close();
  await rm(tempDir, { recursive: true, force: true });
});

async function sha256(filePath: string): Promise<string> {
  const content = await readFile(filePath);
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

describe('agent bridge HTTP API', () => {
  it('reports bridge health', async () => {
    const response = await request(app.server).get('/health').expect(200);

    expect(response.body).toEqual({
      ok: true,
      name: 'html-native-notes-agent-bridge',
      transports: ['http'],
    });
  });

  it('accepts HTML asset registrations through the local HTTP fallback', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-html')
      .send({
        requestId: 'http-html-001',
        filePath: '/Users/example/work/report.html',
        sourceHash: 'sha256:http123',
        title: 'HTTP Report',
        tags: ['AI', ' Report '],
        sourceAgent: 'codex',
        summary: 'Generated by an agent when MCP was unavailable.',
      })
      .expect(202);

    expect(response.body).toMatchObject({
      ok: true,
      type: 'registerHtmlAsset',
      requestId: 'http-html-001',
      dedupeKey: 'registerHtmlAsset:sha256:http123',
    });
    expect(response.body.normalized.tags).toEqual(['ai', 'report']);
    expect(JSON.stringify(response.body)).not.toContain('sk-');
  });

  it('accepts web service registrations through the local HTTP fallback', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-service')
      .send({
        requestId: 'http-service-001',
        title: 'Local Metrics Dashboard',
        cwd: '/Users/example/metrics',
        startCommand: 'npm run dev',
        url: 'http://127.0.0.1:5173',
        port: 5173,
        healthCheckUrl: 'http://127.0.0.1:5173/health',
        envHints: ['DEEPSEEK_API_KEY'],
      })
      .expect(202);

    expect(response.body).toMatchObject({
      ok: true,
      type: 'registerWebService',
      requestId: 'http-service-001',
      dedupeKey: 'registerWebService:http-service-001',
    });
    expect(response.body.normalized.service.startCommand).toBe('npm run dev');
  });

  it('rejects invalid registrations with stable validation errors', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-html')
      .send({
        requestId: 'http-invalid-001',
        filePath: '/Users/example/work/report.pdf',
        sourceHash: 'sha256:http123',
      })
      .expect(400);

    expect(response.body.error.code).toBe('VALIDATION_ERROR');
    expect(response.body.error.message).toBe('Agent bridge request validation failed');
  });

  it('can intake HTTP HTML registrations directly into a Vault manifest when configured', async () => {
    await app.close();

    const vaultDir = path.join(tempDir, 'Vault');
    const sourcePath = path.join(tempDir, 'http-output.html');
    await writeFile(sourcePath, '<!doctype html><title>HTTP Output</title>', 'utf8');

    const sourceHash = await sha256(sourcePath);
    app = await createAgentBridgeHttpServer({ vaultDir });
    await app.ready();

    const response = await request(app.server)
      .post('/api/agent/register-html')
      .send({
        requestId: 'http-vault-001',
        filePath: sourcePath,
        sourceHash,
        title: 'HTTP Output',
        tags: ['bridge'],
      })
      .expect(202);

    expect(response.body).toMatchObject({
      ok: true,
      created: true,
      vaultAssetId: expect.stringMatching(/^asset_/),
      manifestPath: path.join(vaultDir, '.htmlvault', 'manifest.json'),
    });

    const manifest = await readVaultManifest(vaultDir);
    expect(manifest.assets).toHaveLength(1);
    expect(manifest.assets[0]).toMatchObject({
      id: response.body.vaultAssetId,
      sourcePath,
      sourceHash,
    });
  });
});
