// @vitest-environment node

import request from 'supertest';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { createAgentBridgeHttpServer } from '../../../bridge/http/server';

let app: Awaited<ReturnType<typeof createAgentBridgeHttpServer>>;

beforeEach(async () => {
  app = await createAgentBridgeHttpServer();
  await app.ready();
});

afterEach(async () => {
  await app.close();
});

describe('agent bridge HTTP API', () => {
  it('reports bridge health', async () => {
    const response = await request(app.server).get('/health').expect(200);

    expect(response.body).toEqual({
      ok: true,
      name: 'html-native-notes-agent-bridge',
      transports: ['http'],
    });
  });

  it('accepts HTML asset registrations through the local HTTP fallback', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-html')
      .send({
        requestId: 'http-html-001',
        filePath: '/Users/example/work/report.html',
        sourceHash: 'sha256:http123',
        title: 'HTTP Report',
        tags: ['AI', ' Report '],
        sourceAgent: 'codex',
        summary: 'Generated by an agent when MCP was unavailable.',
      })
      .expect(202);

    expect(response.body).toMatchObject({
      ok: true,
      type: 'registerHtmlAsset',
      requestId: 'http-html-001',
      dedupeKey: 'registerHtmlAsset:sha256:http123',
    });
    expect(response.body.normalized.tags).toEqual(['ai', 'report']);
    expect(JSON.stringify(response.body)).not.toContain('sk-');
  });

  it('accepts web service registrations through the local HTTP fallback', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-service')
      .send({
        requestId: 'http-service-001',
        title: 'Local Metrics Dashboard',
        cwd: '/Users/example/metrics',
        startCommand: 'npm run dev',
        url: 'http://127.0.0.1:5173',
        port: 5173,
        healthCheckUrl: 'http://127.0.0.1:5173/health',
        envHints: ['DEEPSEEK_API_KEY'],
      })
      .expect(202);

    expect(response.body).toMatchObject({
      ok: true,
      type: 'registerWebService',
      requestId: 'http-service-001',
      dedupeKey: 'registerWebService:http-service-001',
    });
    expect(response.body.normalized.service.startCommand).toBe('npm run dev');
  });

  it('rejects invalid registrations with stable validation errors', async () => {
    const response = await request(app.server)
      .post('/api/agent/register-html')
      .send({
        requestId: 'http-invalid-001',
        filePath: '/Users/example/work/report.pdf',
        sourceHash: 'sha256:http123',
      })
      .expect(400);

    expect(response.body.error.code).toBe('VALIDATION_ERROR');
    expect(response.body.error.message).toBe('Agent bridge request validation failed');
  });
});
