// @vitest-environment node

import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  convertMarkdownFileToHtml,
  listMarkdownTemplates,
  scanMarkdownFolder,
} from '../../../bridge/markdown/importer';
import { intakeBridgeRequestToVault } from '../../../bridge/vault/intake';
import { buildVaultLibrary } from '../../../bridge/vault/library';
import { readVaultAssetSource } from '../../../bridge/vault/source';

let tempDir: string;
let rootDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(tmpdir(), 'html-native-md-import-'));
  rootDir = path.join(tempDir, 'notes');
  await mkdir(path.join(rootDir, 'research', 'assets'), { recursive: true });
  await writeFile(path.join(rootDir, 'research', 'assets', 'chart.png'), 'image', 'utf8');
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

describe('Markdown import and templates', () => {
  it('offers at least three HTML templates for imported Markdown', () => {
    const templates = listMarkdownTemplates();

    expect(templates.map((template) => template.id)).toEqual(
      expect.arrayContaining(['minimal-diary', 'technical-doc', 'research-report']),
    );
    expect(templates.length).toBeGreaterThanOrEqual(3);
  });

  it('scans Markdown folders while preserving relative folder paths', async () => {
    await writeFile(path.join(rootDir, 'daily.md'), '# Daily\n', 'utf8');
    await writeFile(path.join(rootDir, 'research', 'report.md'), '# Report\n', 'utf8');

    const notes = await scanMarkdownFolder(rootDir);

    expect(notes.map((note) => note.relativePath).sort()).toEqual(['daily.md', 'research/report.md']);
  });

  it('converts frontmatter, images, wikilinks, and code blocks into readable HTML', async () => {
    const markdownPath = path.join(rootDir, 'research', 'report.md');
    await writeFile(
      markdownPath,
      [
        '---',
        'title: Gut Market Research',
        'tags: [research, ai]',
        'summary: Imported from Obsidian',
        '---',
        '# Gut Market Research',
        '',
        'See [[daily]] and [[Uncreated Page]].',
        '',
        '![Chart](./assets/chart.png)',
        '',
        '```ts',
        'const score = 42;',
        '```',
      ].join('\n'),
      'utf8',
    );

    const result = await convertMarkdownFileToHtml({
      rootDir,
      markdownPath,
      templateId: 'research-report',
    });

    expect(result.relativePath).toBe('research/report.md');
    expect(result.frontmatter).toEqual({
      title: 'Gut Market Research',
      tags: ['research', 'ai'],
      summary: 'Imported from Obsidian',
    });
    expect(result.wikilinks).toEqual(['daily', 'Uncreated Page']);
    expect(result.images).toEqual([
      {
        alt: 'Chart',
        src: './assets/chart.png',
        resolvedPath: path.join(rootDir, 'research', 'assets', 'chart.png'),
      },
    ]);
    expect(result.html).toContain('<article class="markdown-import template-research-report">');
    expect(result.html).toContain('<h1>Gut Market Research</h1>');
    expect(result.html).toContain('<a data-wikilink="daily" href="daily.html">daily</a>');
    expect(result.html).toContain('<img src="./assets/chart.png" alt="Chart">');
    expect(result.html).toContain('<pre><code class="language-ts">const score = 42;</code></pre>');
  });

  it('takes over AI-generated Markdown as a Vault asset and previews it as HTML without mutating the source', async () => {
    const vaultDir = path.join(tempDir, 'vault');
    const agentDir = path.join(vaultDir, 'imports', 'codex');
    const markdownPath = path.join(agentDir, 'agent-market-note.md');
    const markdown = [
      '---',
      'title: AI Market Note',
      'tags: [ai, markdown, market]',
      'summary: AI-generated Markdown ready for Vault management',
      '---',
      '# AI Market Note',
      '',
      'Generated by Codex with [[HTML Vault]] references.',
      '',
      '- signal: markdown should be manageable',
    ].join('\n');
    const sourceHash = `sha256:${createHash('sha256').update(markdown).digest('hex')}`;
    await mkdir(agentDir, { recursive: true });
    await writeFile(markdownPath, markdown, 'utf8');

    const intake = await intakeBridgeRequestToVault({
      vaultDir,
      request: {
        requestId: 'req_ai_markdown_takeover',
        type: 'registerMarkdownAsset',
        createdAt: '2026-06-27T00:00:00.000Z',
        sourceAgent: 'codex',
        sourcePath: markdownPath,
        sourceHash,
        title: 'AI Market Note',
        tags: ['agent-output'],
      },
    });

    const library = await buildVaultLibrary({ vaultDir, query: 'markdown market', kinds: ['markdown-note'] });
    const preview = await readVaultAssetSource({ vaultDir, assetId: intake.asset.id });

    expect(intake.asset).toMatchObject({
      kind: 'markdown-note',
      sourcePath: markdownPath,
      sourceHash,
      sourceAgent: 'codex',
    });
    expect(library.items[0]).toMatchObject({
      kind: 'markdown-note',
      title: 'AI Market Note',
      relativeSourcePath: 'imports/codex/agent-market-note.md',
      folderPath: 'imports/codex',
      summary: 'AI-generated Markdown ready for Vault management',
    });
    expect(library.items[0]?.tags).toEqual(expect.arrayContaining(['agent-output', 'ai', 'markdown', 'market']));
    expect(preview).toMatchObject({
      assetId: intake.asset.id,
      title: 'AI Market Note',
      sourcePath: markdownPath,
      sourceHash,
      currentHash: sourceHash,
      sourceHashMatches: true,
    });
    expect(preview.html).toContain('<article class="markdown-import template-technical-doc">');
    expect(preview.html).toContain('<h1>AI Market Note</h1>');
    expect(preview.html).toContain('data-wikilink="HTML Vault"');
  });
});
