// @vitest-environment node

import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { intakeBridgeRequestToVault } from '../../../bridge/vault/intake';
import { buildVaultLibrary } from '../../../bridge/vault/library';

let tempDir: string;
let vaultDir: string;
let aiDir: string;

function sha256(content: string): string {
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

beforeEach(async () => {
  tempDir = await mkdtemp(path.join(tmpdir(), 'html-native-vault-library-'));
  vaultDir = path.join(tempDir, 'Vault');
  aiDir = path.join(vaultDir, 'imports', 'ai-agent');
  await mkdir(aiDir, { recursive: true });
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

describe('Vault Library index', () => {
  it('shows an AI-generated HTML asset as a searchable Vault card with source, tags, folder, summary, and thumbnail status', async () => {
    const htmlPath = path.join(aiDir, 'gut-report.html');
    const html = [
      '<!doctype html>',
      '<html>',
      '<head>',
      '  <title>Gut Market Research</title>',
      '  <meta name="keywords" content="research, ai, gut">',
      '  <meta name="description" content="AI generated market report for gut health tools">',
      '</head>',
      '<body>',
      '  <h1>Gut Market Research</h1>',
      '  <p>Generated by Codex for the AI notes acceptance flow.</p>',
      '</body>',
      '</html>',
    ].join('\n');
    await writeFile(htmlPath, html, 'utf8');

    await intakeBridgeRequestToVault({
      vaultDir,
      request: {
        requestId: 'req_ai_gut',
        type: 'registerHtmlAsset',
        createdAt: '2026-06-27T00:00:00.000Z',
        sourceAgent: 'codex',
        sourcePath: htmlPath,
        sourceHash: sha256(html),
        title: 'Agent supplied title should be refined from HTML',
        tags: ['agent'],
      },
    });

    const library = await buildVaultLibrary({ vaultDir, query: 'gut health', tags: ['research'], sourceAgents: ['codex'] });

    expect(library.items).toHaveLength(1);
    expect(library.items[0]).toMatchObject({
      title: 'Gut Market Research',
      kind: 'html-note',
      source: 'bridge',
      sourceAgent: 'codex',
      sourcePath: htmlPath,
      relativeSourcePath: 'imports/ai-agent/gut-report.html',
      folderPath: 'imports/ai-agent',
      tags: ['agent', 'research', 'ai', 'gut'],
      summary: 'AI generated market report for gut health tools',
      thumbnail: {
        status: 'pending',
        path: path.join(vaultDir, '.htmlvault', 'thumbnails', `${library.items[0]?.id}.png`),
      },
    });
    expect(library.folders).toEqual([
      {
        path: 'imports/ai-agent',
        itemCount: 1,
      },
    ]);
    expect(library.availableFilters.tags).toEqual(['agent', 'ai', 'gut', 'research']);
    expect(library.availableFilters.sourceAgents).toEqual(['codex']);
  });

  it('supports card/list filtering by query, kind, tags, source agent, and folder', async () => {
    const researchPath = path.join(aiDir, 'research.html');
    const dashboardPath = path.join(vaultDir, 'services', 'dashboard.html');
    await mkdir(path.dirname(dashboardPath), { recursive: true });
    const researchHtml = '<html><head><title>Research Brief</title><meta name="keywords" content="research"></head><body></body></html>';
    const dashboardHtml =
      '<html><head><title>Revenue Dashboard</title><meta name="keywords" content="dashboard, finance"></head><body></body></html>';
    await writeFile(researchPath, researchHtml, 'utf8');
    await writeFile(dashboardPath, dashboardHtml, 'utf8');

    await intakeBridgeRequestToVault({
      vaultDir,
      request: {
        requestId: 'req_research',
        type: 'registerHtmlAsset',
        createdAt: '2026-06-27T00:01:00.000Z',
        sourceAgent: 'codex',
        sourcePath: researchPath,
        sourceHash: sha256(researchHtml),
        title: 'Research Brief',
        tags: ['agent'],
      },
    });
    await intakeBridgeRequestToVault({
      vaultDir,
      request: {
        requestId: 'req_dashboard',
        type: 'registerHtmlAsset',
        createdAt: '2026-06-27T00:02:00.000Z',
        sourceAgent: 'cursor',
        sourcePath: dashboardPath,
        sourceHash: sha256(dashboardHtml),
        title: 'Revenue Dashboard',
        tags: ['service'],
      },
    });

    const library = await buildVaultLibrary({
      vaultDir,
      query: 'revenue',
      kinds: ['html-note'],
      tags: ['finance'],
      sourceAgents: ['cursor'],
      folders: ['services'],
    });

    expect(library.items.map((item) => item.title)).toEqual(['Revenue Dashboard']);
    expect(library.items[0]?.relativeSourcePath).toBe('services/dashboard.html');
    expect(library.items[0]?.folderPath).toBe('services');
  });
});
